export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const WALLET_CONNECTED = "WALLET_CONNECTED";
export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const SET_CONTRACT = "SET_CONTRACT";
export const SET_WALLET_BALANCE = "SET_WALLET_BALANCE";
export const SET_NAVBAR_HEADING = "SET_NAVBAR_HEADING";

export const SET_CARDS_FOR_SALE = "SET_CARDS_FOR_SALE";
export const SET_OWNED_CARDS = "SET_OWNED_CARDS";

