export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const SET_CONTRACT = "SET_CONTRACT";
export const SET_WALLET_BALANCE = "SET_WALLET_BALANCE";
export const SET_NAVBAR_HEADING = "SET_NAVBAR_HEADING";
