export const tokens = [
  {
    "key": "0",
    "key_hash": "exprtZBwZUeYYYfUs9B9Rg2ywHezVHnCCnmF9WsDQVrs582dSK63dC",
    "key_binary": "0",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "164",
      "token_id": "0"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T11:32:32Z",
      "height": 653156,
      "block": "BLnrbxySiGGtc6Xka2JXynYrqkjdxEwDfqMhqeXg1nE3NDp3JnJ",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "1",
    "key_hash": "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    "key_binary": "1",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "0",
      "token_id": "1"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T11:49:02Z",
      "height": 653189,
      "block": "BM8ySiYV17WNmms19Wi6iRSYt6Z2tXpmU66pcdk8VCU6bGvPaRS",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "2",
    "key_hash": "expruDuAZnFKqmLoisJqUGqrNzXTvw7PJM2rYk97JErM5FHCerQqgn",
    "key_binary": "2",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "0",
      "token_id": "2"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T11:51:02Z",
      "height": 653193,
      "block": "BLU1GhHk3KdfzSB5eJQfA39qTMpT48uG1FMtkZRavjvT7VDjX2s",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "3",
    "key_hash": "exprujyHLX2vacVy6AcFmAt5K3Y93aMtccrbNtcsCRik6fjxR8wL6x",
    "key_binary": "3",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "1",
      "token_id": "3"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T11:54:32Z",
      "height": 653200,
      "block": "BMRNqygEwhuuGvDHSTosAU3uMgH98R1LaAZovy7MBRvSLwMFg3R",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "4",
    "key_hash": "exprtkcv5vD1Ct4y91FvZFgXVHCxebKhorSVs8hFmXYgmGsEMo4qdp",
    "key_binary": "4",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "2",
      "token_id": "4"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T11:55:02Z",
      "height": 653201,
      "block": "BKieKAtWf6otNFSAqivFYQk2MuHkkehimTsjWLipBqEPiS1wxZm",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "5",
    "key_hash": "exprtqoNj2hRg8PsPMaXLcy3dXjMM3B7nHKrRNqpfjbYpMbULbRj8k",
    "key_binary": "5",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "3",
      "token_id": "5"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:15:52Z",
      "height": 653240,
      "block": "BKtUo8M7WPqPuuaXxE2U1qRpYVnKRCRGaddTgjwimT184S3x9G7",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "6",
    "key_hash": "expruhrcC4osJigCeAywh27e6iYerzr5LnhYDwnWJc7VrLg7SxJbtm",
    "key_binary": "6",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "4",
      "token_id": "6"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:16:22Z",
      "height": 653241,
      "block": "BLxvmmXFWJQxodRvk2KcRvU79TykmnAFTg6h71i9cD9v4HJwjbz",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "7",
    "key_hash": "exprufunBN3FAVpZ21WXquoqiNyWB2PvYy1njkP4wHGtMexdKtcJEM",
    "key_binary": "7",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "5",
      "token_id": "7"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:16:52Z",
      "height": 653242,
      "block": "BLxnvFT7qWkPRvzyqCGrGQd8dhW3WXYrxLfrvu6vrb7kRfsCLHM",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "8",
    "key_hash": "exprtweQBK1emmeg9Q84E7YwE9c8AQrvn88c8SrG2JgjBCYkC1AWx5",
    "key_binary": "8",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "6",
      "token_id": "8"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:17:22Z",
      "height": 653243,
      "block": "BMeHx7hMevTWgyg6PstEjKNFkYNrHWFZUs6F7UiY9YMptZ68c6X",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "9",
    "key_hash": "exprtvAzqNE9zfpBLL9nKEaY1Dd2rznyG9iTFtECJvDkuub1bj3XvW",
    "key_binary": "9",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "7",
      "token_id": "9"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:17:52Z",
      "height": 653244,
      "block": "BMNsgUGDmWYPQzgzdYz9wU7aFXXT8CsjMeRaZumhHsaABjcdm6g",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "10",
    "key_hash": "expruXiL5LQuHx7RcPZztJUFDi93bbuMnKL3AryPqLeM6HkWRAVCeL",
    "key_binary": "10",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "8",
      "token_id": "10"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:18:22Z",
      "height": 653245,
      "block": "BMP7tw26D2REAnAN4g5grGMjGfLBRQ3HGDfGHk4nXt3Te58K28B",
      "is_replaced": false,
      "is_removed": false
    }
  },
  {
    "key": "11",
    "key_hash": "exprugoUUkTmJphCejTLPwF9gbKm2WonYuUBXYqtkc16JVBWe3bdqv",
    "key_binary": "11",
    "value": {
      "card_score": "1",
      "extras": {},
      "player_id": "9",
      "token_id": "11"
    },
    "meta": {
      "contract": "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      "bigmap_id": 14309,
      "time": "2020-08-19T12:18:52Z",
      "height": 653246,
      "block": "BM7gC2qhX6U1bU5fajxn8CvX9QEvBvNBs4nKm2DbhxYSq7yJC8D",
      "is_replaced": false,
      "is_removed": false
    }
  }
]


export const tokensForSale = [
  {
    key: "1",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "4",
    key_hash: "exprtkcv5vD1Ct4y91FvZFgXVHCxebKhorSVs8hFmXYgmGsEMo4qdp",
    key_binary: "4",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:54Z",
      height: 656213,
      block: "BKiwCtjHTAoguBUeHVjpHwZcSdMvDTWeoMpUHTAhackFqZgTrZM",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "2",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "3",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "5",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "6",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "7",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "8",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "9",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "10",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "11",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
  {
    key: "12",
    key_hash: "expru2dKqDfZG8hu4wNGkiyunvq2hdSKuVYtcKta7BWP6Q18oNxKjS",
    key_binary: "1",
    value: { owner: "tz1RMphecUikKpBdojE2f9TzroHhWMEJKYZj", price: "20000" },
    meta: {
      contract: "KT1PeyfZQ5uHyzXzx83t9WGKHk6pKmvcWvLC",
      bigmap_id: 14310,
      time: "2020-08-20T13:12:24Z",
      height: 656212,
      block: "BKvPRpQ5XFq7ebBR4q7Yt1whvbkvWgYtvYZDQrjKhLRQk34QWLW",
      is_replaced: false,
      is_removed: false,
    },
  },
];

export const playerData = [
  {
    _id: { $oid: "5f410424b4fe56321caadc66" },
    batting_stats: [
      {
        "50": "36",
        "100": "5",
        "Batting&Fielding": "Career",
        Mat: "177",
        No: "26",
        Runs: "5412",
        HS: "113",
        Ave: "37.84",
        BF: "4,112",
        SR: "131.61",
        "4s": "480",
        "6s": "190",
        CT: "74",
      },
      {
        "50": "2",
        "100": "1",
        "Batting&Fielding": "2019",
        Mat: "14",
        No: "0",
        Runs: "464",
        HS: "100",
        Ave: "33.14",
        BF: "328",
        SR: "141.46",
        "4s": "46",
        "6s": "13",
        CT: "5",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2018",
        Mat: "14",
        No: "3",
        Runs: "530",
        HS: "92*",
        Ave: "48.18",
        BF: "381",
        SR: "139.10",
        "4s": "52",
        "6s": "18",
        CT: "8",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2017",
        Mat: "10",
        No: "0",
        Runs: "308",
        HS: "64",
        Ave: "30.80",
        BF: "252",
        SR: "122.22",
        "4s": "23",
        "6s": "11",
        CT: "6",
      },
      {
        "50": "7",
        "100": "4",
        "Batting&Fielding": "2016",
        Mat: "16",
        No: "4",
        Runs: "973",
        HS: "113",
        Ave: "81.08",
        BF: "640",
        SR: "152.03",
        "4s": "83",
        "6s": "38",
        CT: "6",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2015",
        Mat: "16",
        No: "5",
        Runs: "505",
        HS: "82*",
        Ave: "45.90",
        BF: "386",
        SR: "130.82",
        "4s": "35",
        "6s": "23",
        CT: "7",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2014",
        Mat: "14",
        No: "1",
        Runs: "359",
        HS: "73",
        Ave: "27.61",
        BF: "294",
        SR: "122.10",
        "4s": "23",
        "6s": "16",
        CT: "7",
      },
      {
        "50": "6",
        "100": "0",
        "Batting&Fielding": "2013",
        Mat: "16",
        No: "2",
        Runs: "634",
        HS: "99",
        Ave: "45.28",
        BF: "457",
        SR: "138.73",
        "4s": "64",
        "6s": "22",
        CT: "7",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2012",
        Mat: "16",
        No: "2",
        Runs: "364",
        HS: "73*",
        Ave: "28.00",
        BF: "326",
        SR: "111.65",
        "4s": "33",
        "6s": "9",
        CT: "7",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2011",
        Mat: "16",
        No: "4",
        Runs: "557",
        HS: "71",
        Ave: "46.41",
        BF: "460",
        SR: "121.08",
        "4s": "55",
        "6s": "16",
        CT: "7",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2010",
        Mat: "16",
        No: "2",
        Runs: "307",
        HS: "58",
        Ave: "27.90",
        BF: "212",
        SR: "144.81",
        "4s": "26",
        "6s": "12",
        CT: "3",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2009",
        Mat: "16",
        No: "2",
        Runs: "246",
        HS: "50",
        Ave: "22.36",
        BF: "219",
        SR: "112.32",
        "4s": "22",
        "6s": "8",
        CT: "9",
      },
      {
        "50": "0",
        "100": "0",
        "Batting&Fielding": "2008",
        Mat: "13",
        No: "1",
        Runs: "165",
        HS: "38",
        Ave: "15.00",
        BF: "157",
        SR: "105.09",
        "4s": "18",
        "6s": "4",
        CT: "2",
      },
    ],
    bowling_stats: [
      {
        Bowling: "Career",
        Mat: "177",
        Balls: "251",
        Runs: "368",
        WKTS: "4",
        BBM: "2/25",
        Ave: "92.00",
        Econ: "8.79",
        SR: "62.75",
        "4W": "0",
      },
      {
        Bowling: "2019",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2018",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2017",
        Mat: "10",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2016",
        Mat: "16",
        Balls: "6",
        Runs: "13",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "13.00",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2015",
        Mat: "16",
        Balls: "11",
        Runs: "10",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "5.45",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2014",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2013",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2012",
        Mat: "16",
        Balls: "18",
        Runs: "49",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "16.33",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2011",
        Mat: "16",
        Balls: "102",
        Runs: "139",
        WKTS: "2",
        BBM: "1/8",
        Ave: "69.50",
        Econ: "8.17",
        SR: "51.00",
        "4W": "0",
      },
      {
        Bowling: "2010",
        Mat: "16",
        Balls: "32",
        Runs: "50",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "9.37",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2009",
        Mat: "16",
        Balls: "36",
        Runs: "46",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "7.66",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2008",
        Mat: "13",
        Balls: "46",
        Runs: "61",
        WKTS: "2",
        BBM: "2/25",
        Ave: "30.50",
        Econ: "7.95",
        SR: "23.00",
        "4W": "0",
      },
    ],
    name: "Virat Kohli",
    image_url: "https://iplstatic.s3.amazonaws.com/players/284/164.png",
    player_id: "164",
    role: "Batsman",
    matches: "14",
    runs: "464",
    wickets: "0",
    batting_style: "Right-handed",
    bowling_style: "Right-arm medium",
    nationality: "Indian",
    dob: "05 November 1988",
    bio:
      "The Indian Cricket Team’s Captain, popularly known as the Run Machine, ViratKohli’s ability and hunger to score daddy hundreds has taken the cricket world by storm. Ranked No. 1 in ODIs, No.2 in Test cricket and No.3 in T20Is is a testimony of how the stylist top-order batsman has evolved over the years. The flamboyant cricketer was the captain of the Indian team that won the 2008 ICC U19 Cricket World Cup and since then there has been no looking back for King Kohli. He is the new-age cricketer who is aggressive and expresses his mind on the field. In 2008, Kohli was inducted in the RCB squad and started leading the side in the year 2013. In the year 2016, he sat atop on the leading run-scorers list, thereby donning the Orange Cap at the end of the ninth edition of the league. The highest paid cricketer in IPL, ViratKohli was the first one to be retained by his franchise ahead of the IPL 2018 Player Auction and will continue to lead his side.",
    team: "Royal Challengers Bangalore",
    __v: 0,
  },
  {
    _id: { $oid: "5f4103a6b4fe56321caadc4f" },
    batting_stats: [
      {
        "50": "36",
        "100": "1",
        "Batting&Fielding": "Career",
        Mat: "188",
        No: "28",
        Runs: "4898",
        HS: "109*",
        Ave: "31.60",
        BF: "3,744",
        SR: "130.82",
        "4s": "431",
        "6s": "194",
        CT: "83",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2019",
        Mat: "15",
        No: "1",
        Runs: "405",
        HS: "67",
        Ave: "28.92",
        BF: "315",
        SR: "128.57",
        "4s": "52",
        "6s": "10",
        CT: "4",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2018",
        Mat: "14",
        No: "2",
        Runs: "286",
        HS: "94",
        Ave: "23.83",
        BF: "215",
        SR: "133.02",
        "4s": "25",
        "6s": "12",
        CT: "8",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2017",
        Mat: "17",
        No: "2",
        Runs: "333",
        HS: "67",
        Ave: "23.78",
        BF: "273",
        SR: "121.97",
        "4s": "31",
        "6s": "9",
        CT: "10",
      },
      {
        "50": "5",
        "100": "0",
        "Batting&Fielding": "2016",
        Mat: "14",
        No: "3",
        Runs: "489",
        HS: "85*",
        Ave: "44.45",
        BF: "368",
        SR: "132.88",
        "4s": "49",
        "6s": "16",
        CT: "2",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2015",
        Mat: "16",
        No: "2",
        Runs: "482",
        HS: "98*",
        Ave: "34.42",
        BF: "333",
        SR: "144.74",
        "4s": "41",
        "6s": "21",
        CT: "5",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2014",
        Mat: "15",
        No: "2",
        Runs: "390",
        HS: "59*",
        Ave: "30.00",
        BF: "302",
        SR: "129.13",
        "4s": "31",
        "6s": "16",
        CT: "5",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2013",
        Mat: "19",
        No: "5",
        Runs: "538",
        HS: "79*",
        Ave: "38.42",
        BF: "409",
        SR: "131.54",
        "4s": "35",
        "6s": "28",
        CT: "7",
      },
      {
        "50": "3",
        "100": "1",
        "Batting&Fielding": "2012",
        Mat: "17",
        No: "2",
        Runs: "433",
        HS: "109*",
        Ave: "30.92",
        BF: "342",
        SR: "126.60",
        "4s": "39",
        "6s": "18",
        CT: "13",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2011",
        Mat: "16",
        No: "3",
        Runs: "372",
        HS: "87",
        Ave: "33.81",
        BF: "297",
        SR: "125.25",
        "4s": "32",
        "6s": "13",
        CT: "7",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2010",
        Mat: "16",
        No: "2",
        Runs: "404",
        HS: "73",
        Ave: "28.85",
        BF: "302",
        SR: "133.77",
        "4s": "36",
        "6s": "14",
        CT: "9",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2009",
        Mat: "16",
        No: "3",
        Runs: "362",
        HS: "52",
        Ave: "27.84",
        BF: "315",
        SR: "114.92",
        "4s": "22",
        "6s": "18",
        CT: "5",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2008",
        Mat: "13",
        No: "1",
        Runs: "404",
        HS: "76*",
        Ave: "36.72",
        BF: "273",
        SR: "147.98",
        "4s": "38",
        "6s": "19",
        CT: "8",
      },
    ],
    bowling_stats: [
      {
        Bowling: "Career",
        Mat: "188",
        Balls: "332",
        Runs: "440",
        WKTS: "15",
        BBM: "4/6",
        Ave: "29.33",
        Econ: "7.95",
        SR: "22.13",
        "4W": "1",
      },
      {
        Bowling: "2019",
        Mat: "15",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2018",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2017",
        Mat: "17",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2016",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2015",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2014",
        Mat: "15",
        Balls: "18",
        Runs: "26",
        WKTS: "1",
        BBM: "1/20",
        Ave: "26.00",
        Econ: "8.66",
        SR: "18.00",
        "4W": "0",
      },
      {
        Bowling: "2013",
        Mat: "19",
        Balls: "8",
        Runs: "6",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "4.50",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2012",
        Mat: "17",
        Balls: "6",
        Runs: "16",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "16.00",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2011",
        Mat: "16",
        Balls: "24",
        Runs: "53",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "13.25",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2010",
        Mat: "16",
        Balls: "114",
        Runs: "153",
        WKTS: "2",
        BBM: "1/19",
        Ave: "76.50",
        Econ: "8.05",
        SR: "57.00",
        "4W": "0",
      },
      {
        Bowling: "2009",
        Mat: "16",
        Balls: "138",
        Runs: "161",
        WKTS: "11",
        BBM: "4/6",
        Ave: "14.63",
        Econ: "7.00",
        SR: "12.54",
        "4W": "1",
      },
      {
        Bowling: "2008",
        Mat: "13",
        Balls: "24",
        Runs: "25",
        WKTS: "1",
        BBM: "1/25",
        Ave: "25.00",
        Econ: "6.25",
        SR: "24.00",
        "4W": "0",
      },
    ],
    name: "Rohit Sharma",
    image_url: "https://iplstatic.s3.amazonaws.com/players/284/107.png",
    player_id: "107",
    role: "Batsman",
    matches: "15",
    runs: "405",
    wickets: "0",
    batting_style: "Right-handed",
    bowling_style: "Right-arm off-spin",
    nationality: "Indian",
    dob: "30 April 1987",
    bio:
      "All eyes will be on this man as he leads Mumbai Indians, the three-time champions of the VIVO IPL. The team in blue and gold are aiming to become the most successful side ever by capturing their fourth title and Rohit Sharma is the most important cog in MI’s wheel. A prolific run-getter, the Hitman is one of the most naturally gifted batsmen in the world.  When it comes to the shorter format, there are few who can match his striking abilities. Rohit proved why he is regarded as a special talent when he became the first batsman to strike two double centuries in the ODIs. He was one of the most consistent Deccan Chargers batsmen in the first three seasons of the IPL, and was instrumental in his former franchise winning the 2009 crown.  However, since 2011, Rohit has been an integral part of the Mumbai Indians guiding their batting line-up. He took over the team’s captaincy a couple of games into the 2013 season and led MI to their maiden IPL title. In the same year, MI also completed a grand double when they clinched the Champions League T20 title. His captaincy was put to test in the 2015 season after the team won just one of their first six games and were struggling to stay afloat. Mumbai Indians then staged a remarkable turnaround and lifted the Trophy for the second time with a convincing win in the final. Rohit, who made a half-century, was named the Player of the Match. The Mumbai Indians finished fifth in the last season and missed out on a playoff berth. They had an up and down season in 2018, but in the 12th edition, they will be looking to start strong and seal a spot in the final four.",
    team: "Mumbai Indians",
    __v: 0,
  },
  {
    _id: { $oid: "5f4104bdb4fe56321caadc86" },
    batting_stats: [
      {
        "50": "23",
        "100": "0",
        "Batting&Fielding": "Career",
        Mat: "190",
        No: "65",
        Runs: "4432",
        HS: "84*",
        Ave: "42.20",
        BF: "3,215",
        SR: "137.85",
        "4s": "297",
        "6s": "209",
        CT: "98",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2019",
        Mat: "15",
        No: "7",
        Runs: "416",
        HS: "84*",
        Ave: "83.20",
        BF: "309",
        SR: "134.62",
        "4s": "22",
        "6s": "23",
        CT: "11",
      },
      {
        "50": "3",
        "100": "0",
        "Batting&Fielding": "2018",
        Mat: "16",
        No: "9",
        Runs: "455",
        HS: "79*",
        Ave: "75.83",
        BF: "302",
        SR: "150.66",
        "4s": "24",
        "6s": "30",
        CT: "11",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2017",
        Mat: "16",
        No: "4",
        Runs: "290",
        HS: "61*",
        Ave: "26.36",
        BF: "250",
        SR: "116.00",
        "4s": "15",
        "6s": "16",
        CT: "10",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2016",
        Mat: "14",
        No: "5",
        Runs: "284",
        HS: "64*",
        Ave: "40.57",
        BF: "210",
        SR: "135.23",
        "4s": "18",
        "6s": "14",
        CT: "8",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2015",
        Mat: "17",
        No: "5",
        Runs: "372",
        HS: "53",
        Ave: "31.00",
        BF: "305",
        SR: "121.96",
        "4s": "27",
        "6s": "17",
        CT: "8",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2014",
        Mat: "16",
        No: "10",
        Runs: "371",
        HS: "57*",
        Ave: "74.20",
        BF: "250",
        SR: "148.40",
        "4s": "22",
        "6s": "20",
        CT: "3",
      },
      {
        "50": "4",
        "100": "0",
        "Batting&Fielding": "2013",
        Mat: "18",
        No: "5",
        Runs: "461",
        HS: "67*",
        Ave: "41.90",
        BF: "283",
        SR: "162.89",
        "4s": "32",
        "6s": "25",
        CT: "15",
      },
      {
        "50": "1",
        "100": "0",
        "Batting&Fielding": "2012",
        Mat: "19",
        No: "5",
        Runs: "358",
        HS: "51*",
        Ave: "29.83",
        BF: "278",
        SR: "128.77",
        "4s": "26",
        "6s": "9",
        CT: "12",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2011",
        Mat: "16",
        No: "4",
        Runs: "392",
        HS: "70*",
        Ave: "43.55",
        BF: "247",
        SR: "158.70",
        "4s": "25",
        "6s": "23",
        CT: "5",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2010",
        Mat: "13",
        No: "2",
        Runs: "287",
        HS: "66*",
        Ave: "31.88",
        BF: "210",
        SR: "136.66",
        "4s": "26",
        "6s": "8",
        CT: "5",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2009",
        Mat: "14",
        No: "5",
        Runs: "332",
        HS: "58*",
        Ave: "41.50",
        BF: "261",
        SR: "127.20",
        "4s": "22",
        "6s": "9",
        CT: "4",
      },
      {
        "50": "2",
        "100": "0",
        "Batting&Fielding": "2008",
        Mat: "16",
        No: "4",
        Runs: "414",
        HS: "65",
        Ave: "41.40",
        BF: "310",
        SR: "133.54",
        "4s": "38",
        "6s": "15",
        CT: "6",
      },
    ],
    bowling_stats: [
      {
        Bowling: "Career",
        Mat: "190",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2019",
        Mat: "15",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2018",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2017",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2016",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2015",
        Mat: "17",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2014",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2013",
        Mat: "18",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2012",
        Mat: "19",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2011",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2010",
        Mat: "13",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2009",
        Mat: "14",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
      {
        Bowling: "2008",
        Mat: "16",
        Balls: "0",
        Runs: "0",
        WKTS: "0",
        BBM: "0/0",
        Ave: "-",
        Econ: "-",
        SR: "-",
        "4W": "0",
      },
    ],
    name: "MS Dhoni",
    image_url: "https://iplstatic.s3.amazonaws.com/players/284/1.png",
    player_id: "1",
    role: "Wicketkeeper batsman",
    matches: "15",
    runs: "416",
    wickets: "0",
    batting_style: "Right-handed",
    bowling_style: "Right-arm medium",
    nationality: "Indian",
    dob: "07 July 1981",
    bio:
      "He was the face of Chennai Super Kings for the first eight editions of the league, leading them to two titles (2010 & 2011) and four runner-up finishes. He then became the first player to be drafted by Rising Pune Supergiant in the ninth edition of the league. And, he once again became the first player to be retained by CSK ahead of the IPL Player Auction 2018.  A batting powerhouse, MS Dhoni possesses the ability to destroy different bowling attacks on his own. The calmness and composure in his demeanor along with a sharp cricketing brain accounts for a lethal combination on the cricketing field and the glistening silverware in the trophy cabinets at CSK are a testimony to his extraordinary leadership skills.",
    team: "Chennai Super Kings",
    __v: 0,
  },
];
